/**
 * 字体大小
 * @type {{}}
 */
export const Font = {
    // 默认大小
    default: {},
    // cell 格的大小
    cell: {
        modalTitle: 18,
        address: 12,
        score: 28,
        radioBtnText: 10,
        testTitle: 12,
        testContent: 12,
        lineTitle: 11,
        tag: 12,
        title: 14,
        cellTitle: 16,
        tabSelected: 16,
        countTime: 14,
        time: 12,
        count: 12,
        countTitle: 11,
        content: 12,
        contentBig: 14,
        sectionTitle: 14,
        homeSectionTitle: 17,
        inputTitle: 12,
        inputContent: 12,
        sectionMore: 12,
        lunboMore: 10,
        lunboTitle: 12,
        status: 12,
        department: 10,
        btnText: 12,
        bigBtnText: 14,
        smalBtnText: 10,
        hjsjDate: 19,
        price: 16,
        countNum: 16,
        deptName: 16,
        jifen: 13,
        userName: 21,
        modalBtnText: 16,
        jcfcCellTitle: 17,
        comment: 15,
    },
    filter: {
        title: 14,
        content: 14,
    },
    // 页面的字体
    page: {
        sectionTitle: 12,
        zhuce: 14,
        pingyin: 12,
        loginText: 14,
        smallContent: 10,
        title: 17,
        ztContent: 14,
        icon: 33,
        jifenNum: 16,
    },
};
