// 各种间隔
export const Margin = {
  bigTop: 19,
  vertical: 10,
  horizontal: 20,
  listCellHorizontal: 19,
  cellContentTop: 17,
  cellContentTop2: 17,
  cellContentTop3: 20,
  cellSmallTop: 6,
  corners: 4,
  bigCorners: 10,
  smalHorizontal: 4,
  midHorizontal: 8,
  btnPaddingHorizontal: 11,
  letterSpacing: 2,
  arrowSize: 15,
  inputRowVertical: 2,
  borderPadding: 10,
  contentRowVertical: 15,
  attachPaddingVertical: 11,
  bigVertical: 8,
  marginLeft: 7,
  bottom: 10,
  rowVertical: 16,
  tabHeight: 40,
  avatarSize: 80,
};
export const Size = {
  fabIconSize: 40,
  avatarSize: 50,
  indicatorSize: 8,
  indicatorSizeSelected: 18,
  arrowSize: 20,
};

export const Style = {
  solid: 'solid',
  tail: 'tail',
  center: 'center',
  column: 'column',
  row: 'row',
  bold: 'bold',
  space_between: 'space-between',
  flex_start: 'flex-start',
  flex_end: 'flex-end',
};
